package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF386B40)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD8E7CB)
val onPrimaryContainerLight = Color(0xFF131F0E)
val secondaryLight = Color(0xFF424940)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD1E8D1)
val onSecondaryContainerLight = Color(0xFF00210B)
val tertiaryLight = Color(0xFF7B545A)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC6979E)
val onTertiaryContainerLight = Color(0xFF523036)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFBFDF8)
val onBackgroundLight = Color(0xFF191C19)
val surfaceLight = Color(0xFFFBFDF8)
val onSurfaceLight = Color(0xFF191C19)
val surfaceVariantLight = Color(0xFFEEF5E9)
val onSurfaceVariantLight = Color(0xFF424940)
val outlineLight = Color(0xFFDEE5D8)
val outlineVariantLight = Color(0xFFDEE5D8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303030)
val inverseOnSurfaceLight = Color(0xFFF3F0F0)
val inversePrimaryLight = Color(0xFFB0CEB4)

val primaryDark = Color(0xFFD8E7CB)
val onPrimaryDark = Color(0xFF131F0E)
val primaryContainerDark = Color(0xFF386B40)
val onPrimaryContainerDark = Color(0xFFD8E7CB)
val secondaryDark = Color(0xFFC7C6C4)
val onSecondaryDark = Color(0xFF30312F)
val secondaryContainerDark = Color(0xFF464745)
val onSecondaryContainerDark = Color(0xFFE3E2E0)
val tertiaryDark = Color(0xFFECBAC1)
val onTertiaryDark = Color(0xFF47272D)
val tertiaryContainerDark = Color(0xFF613D43)
val onTertiaryContainerDark = Color(0xFFFFD9DE)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF191C19)
val onBackgroundDark = Color(0xFFFBFDF8)
val surfaceDark = Color(0xFF191C19)
val onSurfaceDark = Color(0xFFFBFDF8)
val surfaceVariantDark = Color(0xFF424940)
val onSurfaceVariantDark = Color(0xFFEEF5E9)
val outlineDark = Color(0xFF8D938B)
val outlineVariantDark = Color(0xFF424940)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE4E2E1)
val inverseOnSurfaceDark = Color(0xFF303030)
val inversePrimaryDark = Color(0xFF4A654F)

val surfaceContainerLowest = Color(0xFFFFFFFF)
val surfaceContainerLow = Color(0xFFF6F3F2)
val surfaceContainer = Color(0xFFF0EDED)
val surfaceContainerHigh = Color(0xFFEAE8E7)
val surfaceContainerHighest = Color(0xFFF3F4EE)
